model:
  in-channels: 3
  perception:
    out-channels: 3
    filters:
      - SOLVER_X
      - SOLVER_Y
      - IDENTITY

logger:
  name: ca-growth-model
  path: logs
  level: INFO
  message_format: "%(levelname)s %(asctime)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"